# MODELOS

IMPORTACION DE LIBRERIAS

In [2]:
# Bibliotecas estándar
import os
import joblib
import concurrent.futures
import re
import random
from collections import Counter
from datetime import datetime

# Bibliotecas científicas
import numpy as np

# Bibliotecas de análisis y modelado de datos
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_absolute_error, mean_squared_error, classification_report, confusion_matrix, roc_auc_score, accuracy_score
from sklearn.model_selection import TimeSeriesSplit

# Librerias de modelos
#from statsmodels.tsa.statespace.sarimax import SARIMAX
from xgboost import XGBRegressor, XGBClassifier
from prophet import Prophet
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Bibliotecas de visualización
from imblearn.over_sampling import SMOTE, BorderlineSMOTE
from imblearn.under_sampling import RandomUnderSampler


c:\Users\jpetit.sta\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


CARGA DE DATOS

In [3]:
df = pd.read_csv(r'.\..\..\Datos_Proyecto\observations_full.csv')

df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

SVM

In [14]:
# Select features and target
features = ['year', 'month', 'day', 'precipitation', 'wind', 'humidity', 'estacion_id']
target = 'weather_id'

# Split data into train and test sets
X = df[features]
y = df[target]

# Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42, stratify=y_res)

# Scale the data (using StandardScaler)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = SVC(probability=True, C=0.1, gamma='scale', kernel='rbf', class_weight='balanced')
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ROC AUC (for multi-class)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test_scaled), multi_class='ovr')
print(f"ROC AUC: {roc_auc}")

# Save the model using joblib
joblib.dump(model, r'.\..\Modelos\SVM_weather_id.pkl')

Accuracy: 0.8421385637456501
Classification Report:
              precision    recall  f1-score   support

           1       0.84      0.87      0.86      1897
           2       0.83      0.84      0.84      1896
           3       0.75      0.57      0.65      1897
           4       0.86      0.97      0.91      1897
           5       0.89      0.97      0.93      1896

    accuracy                           0.84      9483
   macro avg       0.84      0.84      0.84      9483
weighted avg       0.84      0.84      0.84      9483

Confusion Matrix:
[[1643    5  156   93    0]
 [  18 1587  197   94    0]
 [ 264  280 1078   71  204]
 [  21   32    0 1831   13]
 [   0    0    0   49 1847]]
ROC AUC: 0.9690939074866127


['.\\..\\Modelos\\SVM_weather_id.pkl']

XGBoosting Classifier

In [6]:
# Seleccionar las características y el objetivo
features = ['year', 'month', 'day', 'precipitation', 'wind', 'humidity', 'estacion_id']
target = 'weather_id'

# Dividir los datos en características (X) y objetivo (y)
X = df[features]
y = df[target]

# Ajustar las etiquetas para que comiencen desde 0
y_adjusted = y - 1  # Ahora las clases estarán en el rango [0, 1, 2, 3, 4]

# Mostrar la distribución original de las clases
print("Distribución original de las clases:", Counter(y_adjusted))

# Crear una instancia de SMOTE
smote = SMOTE(random_state=42, k_neighbors=10)
X_resampled, y_resampled = smote.fit_resample(X, y_adjusted)

# Mostrar la nueva distribución de las clases
print("Distribución de clases después de SMOTE:", Counter(y_resampled))

# Dividir los datos balanceados en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Crear un modelo de XGBoost
model = XGBClassifier(random_state=42, n_estimators=300, max_depth=30)

# Ajustar el modelo con los datos de entrenamiento balanceados
model.fit(X_train, y_train)

# Realizar predicciones sobre el conjunto de prueba
y_pred = model.predict(X_test)

# Reconvertir las predicciones y las etiquetas originales
y_pred = y_pred + 1  # Volver a [1, 2, 3, 4, 5]
y_test = y_test + 1  # Volver a [1, 2, 3, 4, 5]

# Calcular la exactitud (accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Evaluar el rendimiento del modelo
print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

# Mostrar la matriz de confusión
print("\nMatriz de confusión:")
print(confusion_matrix(y_test, y_pred))

# Guardar el modelo entrenado usando joblib
joblib.dump(model, r'.\..\Modelos\XGB_weather_id.pkl')

Distribución original de las clases: Counter({1: 9483, 0: 9024, 2: 5959, 3: 429, 4: 105})
Distribución de clases después de SMOTE: Counter({0: 9483, 2: 9483, 1: 9483, 3: 9483, 4: 9483})
Accuracy: 0.9244964673626489

Reporte de clasificación:
              precision    recall  f1-score   support

           1       0.89      0.97      0.93      1897
           2       0.89      0.96      0.92      1910
           3       0.93      0.71      0.80      1861
           4       0.93      0.98      0.95      1892
           5       0.99      1.00      0.99      1923

    accuracy                           0.92      9483
   macro avg       0.93      0.92      0.92      9483
weighted avg       0.93      0.92      0.92      9483


Matriz de confusión:
[[1847    1   29   20    0]
 [   1 1825   58   26    0]
 [ 203  215 1320   97   26]
 [  13   14   12 1852    1]
 [   0    0    0    0 1923]]


['.\\..\\Modelos\\XGB_weather_id.pkl']

RANDOM FOREST CLASSIFIER

In [12]:
# Seleccionar las características y el objetivo
features = ['year', 'month', 'day', 'precipitation', 'wind', 'humidity', 'estacion_id']
target = 'weather_id'

# Dividir los datos en características (X) y objetivo (y)
X = df[features]
y = df[target]

# Ajustar las etiquetas para que comiencen desde 0
y_adjusted = y - 1  # Ahora las clases estarán en el rango [0, 1, 2, 3, 4]

# Mostrar la distribución original de las clases
print("Distribución original de las clases:", Counter(y_adjusted))

# Crear una instancia de SMOTE
smote = SMOTE(random_state=42,k_neighbors=10)
X_resampled, y_resampled = smote.fit_resample(X, y_adjusted)

# Mostrar la nueva distribución de las clases
print("Distribución de clases después de SMOTE:", Counter(y_resampled))

# Dividir los datos balanceados en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Crear un modelo de Random Forest (puedes usar cualquier otro clasificador)
model = RandomForestClassifier(random_state=42, n_estimators=300, max_depth=30)

# Ajustar el modelo con los datos de entrenamiento balanceados
model.fit(X_train, y_train)

# Realizar predicciones sobre el conjunto de prueba
y_pred = model.predict(X_test)

# Reconvertir las predicciones y las etiquetas originales
y_pred = y_pred + 1  # Volver a [1, 2, 3, 4, 5]
y_test = y_test + 1  # Volver a [1, 2, 3, 4, 5]

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Evaluar el rendimiento del modelo
print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

# Mostrar la matriz de confusión
print("\nMatriz de confusión:")
print(confusion_matrix(y_test, y_pred))

# Guardar el modelo entrenado usando joblib
#joblib.dump(model, r'.\..\Modelos\RFC_weather_id.pkl')

Distribución original de las clases: Counter({1: 9483, 0: 9024, 2: 5959, 3: 429, 4: 105})
Distribución de clases después de SMOTE: Counter({0: 9483, 2: 9483, 1: 9483, 3: 9483, 4: 9483})
Accuracy: 0.9128967626278603

Reporte de clasificación:
              precision    recall  f1-score   support

           1       0.87      0.99      0.92      1897
           2       0.87      0.98      0.92      1910
           3       0.97      0.62      0.76      1861
           4       0.90      0.98      0.94      1892
           5       0.98      1.00      0.99      1923

    accuracy                           0.91      9483
   macro avg       0.92      0.91      0.91      9483
weighted avg       0.92      0.91      0.91      9483


Matriz de confusión:
[[1870    0    9   18    0]
 [   0 1864   17   29    0]
 [ 265  253 1155  156   32]
 [  18   19    9 1846    0]
 [   0    0    1    0 1922]]


RNN

In [11]:
# 1. Importar las bibliotecas necesarias
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# 2. Seleccionar características y objetivo
features = ['year', 'month', 'day', 'precipitation', 'wind', 'humidity', 'estacion_id']
target = 'weather_id'

# Dividir en X (características) y y (objetivo)
X = df[features]
y = df[target]

# 3. Preprocesamiento de datos
# Normalizar las características numéricas
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Codificar el objetivo (y) en formato "one-hot"
y_encoded = to_categorical(y)

# 4. Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

# 5. Crear la arquitectura de la Red Neuronal
model = Sequential()
model.add(Dense(256, input_dim=X_train.shape[1], activation='relu'))  # Más neuronas para mayor capacidad de aprendizaje
model.add(Dropout(0.3))  # Regularización para evitar sobreajuste
model.add(Dense(128, activation='relu'))  # Segunda capa oculta
model.add(Dropout(0.3))  # Más regularización
model.add(Dense(64, activation='relu'))  # Tercera capa oculta
model.add(Dense(y_encoded.shape[1], activation='softmax'))  # Capa de salida para clasificación multiclase

# 6. Compilar el modelo
model.compile(optimizer='adam', 
              loss='categorical_crossentropy',  # Función de pérdida para clasificación multiclase
              metrics=['accuracy'])

# 7. Entrenar el modelo
history = model.fit(X_train, y_train, 
                    validation_data=(X_test, y_test), 
                    epochs=50,  # Más épocas para mejor ajuste
                    batch_size=64,  # Tamaño del lote
                    verbose=2)

# 8. Evaluar el modelo
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f'\nPérdida en prueba: {test_loss}')
print(f'Precisión en prueba: {test_accuracy}')

# 9. Realizar predicciones
predictions = model.predict(X_test)

# Decodificar las predicciones de vuelta a sus clases originales
predicted_classes = predictions.argmax(axis=1)

# Decodificar las etiquetas reales (y_test) si están en formato one-hot
y_test_classes = y_test.argmax(axis=1)

# 10. Calcular y mostrar métricas adicionales
cm = confusion_matrix(y_test_classes, predicted_classes)
print("\nMatriz de Confusión:")
print(cm)

print("\nReporte de Clasificación:")
print(classification_report(y_test_classes, predicted_classes))

# 11. Guardar el modelo entrenado
#model.save(r'.\..\Modelos\RNN_weather_id_v2.h5')


Epoch 1/50


c:\Users\jpetit.sta\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


313/313 - 2s - 7ms/step - accuracy: 0.7765 - loss: 0.6270 - val_accuracy: 0.8554 - val_loss: 0.4472
Epoch 2/50
313/313 - 1s - 2ms/step - accuracy: 0.8433 - loss: 0.4630 - val_accuracy: 0.8742 - val_loss: 0.3980
Epoch 3/50
313/313 - 1s - 2ms/step - accuracy: 0.8577 - loss: 0.4241 - val_accuracy: 0.8758 - val_loss: 0.3833
Epoch 4/50
313/313 - 1s - 2ms/step - accuracy: 0.8626 - loss: 0.4099 - val_accuracy: 0.8752 - val_loss: 0.3807
Epoch 5/50
313/313 - 1s - 2ms/step - accuracy: 0.8691 - loss: 0.3942 - val_accuracy: 0.8768 - val_loss: 0.3710
Epoch 6/50
313/313 - 1s - 2ms/step - accuracy: 0.8707 - loss: 0.3864 - val_accuracy: 0.8820 - val_loss: 0.3611
Epoch 7/50
313/313 - 1s - 2ms/step - accuracy: 0.8738 - loss: 0.3795 - val_accuracy: 0.8752 - val_loss: 0.3639
Epoch 8/50
313/313 - 1s - 2ms/step - accuracy: 0.8763 - loss: 0.3711 - val_accuracy: 0.8812 - val_loss: 0.3563
Epoch 9/50
313/313 - 1s - 2ms/step - accuracy: 0.8773 - loss: 0.3716 - val_accuracy: 0.8832 - val_loss: 0.3588
Epoch 10/50


c:\Users\jpetit.sta\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jpetit.sta\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\jpetit.sta\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_

# PREDICCIONES

Mejor modelo para weather_id: **Random Forest Classifier**

In [ ]:
# Cargar el DataFrame y convertir la columna de fecha
predictions = pd.read_csv(r'.\..\weather_predictions.csv')
predictions['date'] = pd.to_datetime(predictions['date'])

# Extraer año, mes y día de la fecha
predictions['year'] = predictions['date'].dt.year
predictions['month'] = predictions['date'].dt.month
predictions['day'] = predictions['date'].dt.day

# Cargar el modelo
modelo_RFC = joblib.load(r'.\..\Modelos\RandomForest\Classifier\weather_id_RFC.pkl')

# Seleccionar las características requeridas para el modelo
features = [
    'year', 'month', 'day', 'precipitation', 'temp_max', 'temp_min',
    'wind', 'humidity', 'pressure', 'solar_radiation', 'visibility', 'cloudiness_id'
]

# Crear la matriz de características para el modelo
X = predictions[features]

# Generar predicciones con el modelo
predictions['weather_id'] = modelo_RFC.predict(X).round(0).astype(int)

# Guardar el DataFrame actualizado
predictions.to_csv(r'.\..\weather_predictions.csv', index=False)
